// src/pages/works/index.vue
<template lang="pug">
  div(class="container")
    main(class="main")
      common-title
        span WORKS
        span お仕事の実績や、自主制作のまとめページです
      div(class="works__filter")
        div(class="works__filterChild")
          select(class="works__filterSelect" v-model="currentCategory")
            option(value="") Category
            option(v-for="category in worksCategory" :key="category.id" :value="category.category_slug") {{category.category_label}}
        div(class="works__filterChild")
          select(class="works__filterSelect" v-model="currentTechnology")
            option(value="") Technology
            option(v-for="technology in worksTechnology" :key="technology.id" :value="technology.technology_slug") {{technology.technology_label}}
      WorksList(:currentCategory="currentCategory" :currentTechnology="currentTechnology")
      footer(class="works__footer")
        div(class="works__back")
          common-icon-btn(:title="'BACK TO TOP'" link="/" :blank="false" :icon="['fas', 'home']" color="'#4267B2'")
</template>

<script>
import { mapState } from 'vuex'
import CommonTitle from '@/components/CommonTitle'
import CommonIconBtn from '@/components/CommonIconBtn'
import IconQiita from '@/components/icons/IconQiita'
import IconHatena from '@/components/icons/IconHatena'
import WorksList from '@/components/WorksList'

export default {
  components: {
    CommonTitle,
    CommonIconBtn,
    IconQiita,
    IconHatena,
    WorksList,
  },
  data() {
    return {
      currentCategory: '',
      currentTechnology: '',
    }
  },
  computed: {
    ...mapState(['worksCategory', 'worksTechnology']),
  },
  methods: {
    setCurrenCategory(e) {
      console.log(e)
    },
    setCurrentTechnology(e) {
      console.log(e)
    },
  },
  head() {
    return this.$setMeta({
      title: 'WORKS | HTMLGO',
      description: '実績を紹介しています。',
      url: 'https://htmlgo.site/works/',
    })
  },
}
</script>

<style lang="scss" scoped>
$works_bp: 700px;

.main {
  max-width: 900px;
  margin: 0 auto var(--s20);
  padding: 0 var(--s5);
}
.works__filter {
  display: flex;
  margin: 0 0 var(--s5);
  @include max-screen($works_bp) {
    display: block;
  }
}

.works__filterChild {
  position: relative;
  &:before {
    position: absolute;
    right: 10px;
    top: 0;
    bottom: 0;
    margin: auto;
    content: '';
    display: block;
    transform: rotate(45deg) translate(-1px, -1px);
    width: 5px;
    height: 5px;
    border-right: 2px solid #000;
    border-bottom: 2px solid #000;
  }
}
.works__filterChild:not(:last-of-type) {
  margin-right: 20px;
  @include max-screen($works_bp) {
    margin-right: 0;
    margin-bottom: 10px;
  }
}
.works__filterSelect {
  position: relative;
  outline: none;
  text-indent: 0.01px;
  text-overflow: '';
  background: none transparent;
  vertical-align: middle;
  font-size: inherit;
  color: inherit;
  appearance: none;
  border-radius: none;
  height: 2.2em;
  font-size: 1.6rem;
  padding: 0 35px 0 10px;
  cursor: pointer;
  @include max-screen($works_bp) {
    width: 100%;
  }
}
.works__footer {
  border-top: 1px solid var(--borderColor);
  padding-top: var(--s11);
  margin-top: var(--s11);
}
.works__back {
  text-align: center;
}
</style>

// src/pages/works/index.tsx
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

// type
import { WorksPosts } from 'types/index'

// libs
import { event } from 'libs/gtag'
import { worksGetStaticProps } from 'libs/getStaticProps'

// components
import HeadWrap from 'components/headWrap'
import Layout from 'components/layout'
import Title from 'components/title'
import IconBtn from 'components/IconBtn'
import WorksList from 'components/worksList'

type Props = {
  works: WorksPosts
  categories: { category_label: string; category_slug: string }[]
  technologies: { technology_label: string; technology_slug: string }[]
}

const className = {
  main: 'mx-20px max-w-[800px] md:mx-auto',
  filter: `mb-20px md:flex`,
  filterChild: `
    mb-10px
    mr-0px
    md:mr-20px
    md:mb-0px
    relative
    block
    before:absolute
    before:before:content-[""]
    before:my-auto
    before:top-[0px]
    before:bottom-[0px]
    before:right-[10px]
    before:w-[5px]
    before:h-[5px]
    before:border-r-[2px]
    before:border-b-[2px]
    before:block
    before:rotate:45deg
    before:x-[-1px]
    before:y-[-1px]
    before:rotate-45
    before:z-[1]
  `,
  filterSelect: `
    w-[100%]
    md:w-[auto]
    relative
    outline-none
    text-overflow-['']
    appearance-none
    rounded-none
    h-[30px]
    border-1
    border-[#000]
    pr-[35px]
    pl-[10px]
  `,
  footer: `border-border border-t-[1px] pt-40px pb-40px mt-40px`,
  back: `text-center`,
}

export default function Works({ works, categories = [], technologies = [] }: Props) {
  const router = useRouter()
  const [filters, setFilters] = useState({
    category: '',
    technology: '',
  })

  const categoryHandler = (e: React.ChangeEvent<HTMLSelectElement>): void => {
    const { value } = e.currentTarget
    const { technology } = router.query
    router.push({
      query: {
        ...(value ? { category: value } : {}),
        ...(technology ? { technology } : {}),
      },
    })
  }

  const technologyHandler = (e: React.ChangeEvent<HTMLSelectElement>): void => {
    const { value } = e.currentTarget
    const { category } = router.query
    router.push({
      query: { ...(category ? { category } : {}), ...(value ? { technology: value } : {}) },
    })
  }

  const clickHandler = (label: string, value: string) => {
    event({ action: 'click', category: 'works', label, value })
  }

  const filterPost = (): WorksPosts => {
    const { category, technology } = filters
    return works.filter((work) => {
      const categoryMatch = category === '' || work.category.map((c) => c.category_slug).includes(category)
      const technologyMatch =
        technology === '' || work.technology.map((c) => c.technology_slug).includes(technology)

      return categoryMatch && technologyMatch
    })
  }

  const changeToString = (param: string | string[] | undefined): string => {
    if (Array.isArray(param)) {
      return param[0]
    } else if (param === undefined) {
      return ''
    }
    return param
  }

  useEffect(() => {
    // パラメータを取ってくる
    if (router.isReady) {
      const { category, technology } = router.query
      setFilters({
        category: changeToString(category),
        technology: changeToString(technology),
      })
    }
  }, [router])

  return (
    <Layout>
      <HeadWrap
        title={'WORKS | HTMLGO'}
        description={'実績を紹介しています'}
        url={`https://htmlgo.site/works/`}
      />
      <main className={className.main}>
        <Title title="WORKS" text="最新のお仕事の実績や、自主制作" />
        <div className={className.filter}>
          <div className={className.filterChild}>
            <select className={className.filterSelect} onChange={categoryHandler} value={filters.category}>
              <option value="" key={''}>
                Category
              </option>
              {categories.map((c) => (
                <option value={c.category_slug} key={c.category_slug}>
                  {c.category_label}
                </option>
              ))}
            </select>
          </div>
          <div className={className.filterChild}>
            <select
              className={className.filterSelect}
              onChange={technologyHandler}
              value={filters.technology}
            >
              <option value="" key={''}>
                Technology
              </option>
              {technologies.map((c) => (
                <option value={c.technology_slug} key={c.technology_slug}>
                  {c.technology_label}
                </option>
              ))}
            </select>
          </div>
        </div>
        <WorksList works={filterPost()} clickHandler={clickHandler} />
        <footer className={className.footer}>
          <div className={className.back}>
            <IconBtn
              icon="faHome"
              link="/"
              color="#ffffff"
              onClick={() => {
                clickHandler('top', '/')
              }}
            />
          </div>
        </footer>
      </main>
    </Layout>
  )
}

export const getStaticProps = worksGetStaticProps
