// src/pages/contact/thanks.vue
<template lang="pug">
  div(class="container")
    main(class="main")
      common-title
        | CONTACT
      div(class="contact__body")
        div(class="contact__thanks")
          | お問い合わせありがとうございました。<br>内容を確認後、折り返しご連絡いたしますので、<br>今しばらくおまちください。

      div(class="contact__back")
        common-icon-btn(:title="'BACK TO TOP'" link="/" :blank="false" :icon="['fas', 'home']" color="'#4267B2'")
</template>

<script>
import CommonTitle from '@/components/CommonTitle'
import CommonIconBtn from '@/components/CommonIconBtn'
import SnsBox from '@/components/SnsBox'

export default {
  components: {
    CommonTitle,
    CommonIconBtn,
    SnsBox,
  },
  head() {
    const meta = this.$setMeta({
      title: 'CONTACT | HTMLGO',
      description: 'お問い合わせ',
      url: 'https://htmlgo.site/contact/',
    })
    return {
      ...meta,
    }
  },
}
</script>

<style lang="scss" scoped>
$about_bp: 800px;

.main {
  width: 720px;
  margin: 0 auto var(--s20);

  @include max-screen($about_bp) {
    width: auto;
    margin: 0 var(--s5) var(--s10);
  }
}

.contact__body {
  max-width: 600px;
  padding: 0 var(--s5) var(--s10);
  border-bottom: 1px solid var(--borderColor);
  margin: 0 auto var(--s10);
}

.contact__thanks {
  font-size: 2rem;
  text-align: center;
  line-height: 1.6;
}

.contact__back {
  text-align: center;
}
</style>

// src/pages/contact/thanks.tsx
// styles
import styles from 'styles/page/Thanks.module.scss'

// libs
import { event } from 'libs/gtag'

// components
import HeadWrap from 'components/headWrap'
import Layout from 'components/layout'
import Title from 'components/title'
import IconBtn from 'components/IconBtn'

const className = {
  main: 'mx-20px',
  body: `max-w-[600px] mx-auto mb-40px`,
  thanks: `text-16px text-center md:text-20px`,
  back: `border-border border-t-[1px] text-center pt-40px pb-40px mt-40px md:pb-80px`,
}

export default function Thanks() {
  const clickHandler = (label: string, value: string) => {
    event({ action: 'click', category: 'contact-thanks', label, value })
  }
  return (
    <Layout>
      <HeadWrap
        title={'THANKS | HTMLGO'}
        description={'お問い合わせ'}
        url={`https://htmlgo.site/contact/thanks/`}
      />
      <main className={className.main}>
        <Title title="THANKS" text="お問合せありがとうございました" />
        <div className={className.body}>
          <div className={className.thanks}>
            お問い合わせありがとうございました。
            <br />
            内容を確認後、折り返しご連絡いたしますので、
            <br />
            今しばらくおまちください。
          </div>
        </div>
        <div className={className.back}>
          <IconBtn
            icon="faHome"
            title="back to top"
            link="/"
            color="#ffffff"
            onClick={() => {
              clickHandler('top', '/')
            }}
          />
        </div>
      </main>
    </Layout>
  )
}
