// src/pages/index.vue
<template lang="pug">
  div(class="container")
    main(class="main")
      section(class="section")
        div(class="mainVisual")
          main-title
        div(class="section__btn")
          common-text-btn(title="WHO ?" link="/about/")
      section(class="section")
        common-title
          span WORKS
          span 最新のお仕事の実績や、自主制作
        works-list(:worksLength="3")
        div(class="section__btn")
          common-text-btn(title="MORE" link="/works/")
      section(class="section")
        common-title
          span ARTICLES
          span 最新の記事
        feed-panel(:isPagenagtion="false")
        div(class="section__btn")
          common-text-btn(title="MORE" link="/articles/")
</template>

<script>
import CommonTitle from '@/components/CommonTitle'
import CommonTextBtn from '@/components/CommonTextBtn'
import FeedPanel from '@/components/FeedPanel'
import WorksList from '@/components/WorksList'
import MainTitle from '@/components/MainTitle'

export default {
  components: {
    CommonTitle,
    CommonTextBtn,
    FeedPanel,
    WorksList,
    MainTitle,
  },
  head() {
    return this.$setMeta({
      topFlag: true,
      title: 'TOP | HTMLGO',
      description: 'WEB技術を書き連ねるサイト',
      url: 'https://htmlgo.site/',
    })
  },
}
</script>

<style lang="scss" scoped>
$top_bp: 800px;
.main {
  max-width: 900px;
  margin: 0 auto 0;
  min-height: 300px;
  padding: 0 var(--s7) 0;
}
.section {
  border-bottom: 1px solid var(--borderColor);
  padding: 0 0 var(--s10);
  margin: 0 0 var(--s20);
  @include max-screen($top_bp) {
    padding: 0 0 var(--s5);
    margin: 0 0 var(--s10);
  }
}
.section__btn {
  text-align: center;
}
.mainVisual {
  text-align: center;
  background: var(--mainColor);
  padding: var(--s22) var(--s7);
  margin: 0 0 var(--s12);
  svg {
    max-width: 100%;
    box-sizing: border-box;
  }
  @include max-screen($top_bp) {
    padding: var(--s10) var(--s7);
    margin: 0 0 var(--s6);
  }
}
</style>

// src/pages/index.tsx
import React from 'react'
import { useSelector } from 'react-redux'

// store
import { RootState } from '../store'

// type
import { WorksPosts, FeedObj } from 'types/index'

// libs
import { event } from 'libs/gtag'

// components
import ViewSwitch from 'components/viewSwitch'
import HeadWrap from 'components/headWrap'
import Layout from 'components/layout'
import Title from 'components/title'
import TextBtn from 'components/textBtn'
import WorksList from 'components/worksList'
import Panels from 'components/panels'
import { topGetStaticProps } from 'libs/getStaticProps'

type Props = {
  works: WorksPosts
  articles: FeedObj[]
}

const className = {
  main: 'mx-20px max-w-[800px] md:mx-auto',
  btnWrap: 'text-center',
  section: 'mb-40px pb-20px md:mb-80px md:pb-40px border-b-1 border-border',
}

export default function Home({ works = [], articles = [] }: Props) {
  const type = useSelector((state: RootState) => state.panelType.value)

  const clickHandler = (label: string, value: string) => {
    event({ action: 'click', category: 'top', label, value })
  }

  return (
    <Layout>
      <HeadWrap
        title={'TOP | HTMLGO'}
        description={'WEB技術を書き連ねるサイト'}
        url={`https://htmlgo.site/`}
        isTop={true}
      />
      <main className={className.main}>
        {/* articles */}
        <section className={className.section}>
          <Title title="ARTICLES" text="最新の記事" />
          <ViewSwitch type={type} />
          <Panels articles={articles} type={type} clickHandler={clickHandler} />
          <div className={className.btnWrap}>
            <TextBtn
              title="MORE"
              link="/articles/"
              onClick={() => {
                clickHandler('article-index', '/articles/')
              }}
            />
          </div>
        </section>
        {/* works */}
        <section className={className.section}>
          <Title title="WORKS" text="最新のお仕事の実績や、自主制作" />
          <WorksList works={works} clickHandler={clickHandler} />
          <div className={className.btnWrap}>
            <TextBtn
              title="MORE"
              link="/works/"
              onClick={() => {
                clickHandler('works-index', '/works/')
              }}
            />
          </div>
        </section>
      </main>
    </Layout>
  )
}

export const getStaticProps = topGetStaticProps
